apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
  labels:
    app: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - name: django-container
        image: oluwafemi99/django-messaging-app:v2.0
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: messaging_app.settings
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: django-blue
spec:
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
