pipeline {
    agent any

    tools {
        // ShiningPanda provides Python virtualenv
        python 'Python3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/Oluwafemi99/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python -m venv venv'
                sh '. venv/bin/activate && pip install -U pip setuptools wheel'
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest --junitxml=report.xml'
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }

    triggers {
        // Manual trigger only — remove GitHub webhook
        // Build Now button will trigger
    }
}
