services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # expose internally, no need to bind to host 3306 to avoid port conflict
      - "3306:3306"  # only if you want to connect from host
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:
